version: '3'
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: starsoft_backend_challenge_db_user
      POSTGRES_PASSWORD: BgbsQ55kXuUhTmxA8XXsnYpYPDNg17qm
      POSTGRES_DB: starsoft_backend_challenge_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    environment:
      - REDIS_PASSWORD=Adi6AAIjcDFiYzVhNDkwM2E4YmQ0MjJiOWU4N2VjN2FiM2Y4N2Y4OHAxMA
    command: ["redis-server", "--requirepass", "$REDIS_PASSWORD"]

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

volumes:
  postgres_data:
